"""Compose an insertion scene: SO-101 arm + a boss part + a socket part.

The two parts are generated by shape_gen (see shape_gen.py) and stitched together
with the SO-101 model into one MuJoCo model. build_model_spec() returns the model
plus the motion heights the scripted expert (expert.py) needs.

The composed XML is written INTO the SO-101 model dir so its relative mesh paths
(meshdir="assets") resolve.
"""

import os
import xml.etree.ElementTree as ET

import mujoco
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
MODEL_DIR = os.path.join(REPO, "demo", "menagerie", "robotstudio_so101")
SCENE_TMP = os.path.join(MODEL_DIR, "_insertion_scene_tmp.xml")


def _scene_skeleton():
    """Shared scene head: include arm, gravity, visuals, ground. Returns (root, asset, worldbody)."""
    m = ET.Element("mujoco", {"model": "insertion"})
    ET.SubElement(m, "include", {"file": "so101.xml"})
    ET.SubElement(m, "option", {"gravity": "0 0 -9.81"})
    visual = ET.SubElement(m, "visual")
    ET.SubElement(visual, "headlight", {"diffuse": "0.6 0.6 0.6", "ambient": "0.3 0.3 0.3", "specular": "0 0 0"})
    ET.SubElement(visual, "global", {"azimuth": "160", "elevation": "-20"})
    asset = ET.SubElement(m, "asset")
    ET.SubElement(asset, "texture", {"type": "skybox", "builtin": "gradient",
                                     "rgb1": "0.3 0.5 0.7", "rgb2": "0 0 0", "width": "512", "height": "3072"})
    ET.SubElement(asset, "texture", {"type": "2d", "name": "groundplane", "builtin": "checker", "mark": "edge",
                                     "rgb1": "0.2 0.3 0.4", "rgb2": "0.1 0.2 0.3", "markrgb": "0.8 0.8 0.8",
                                     "width": "300", "height": "300"})
    ET.SubElement(asset, "material", {"name": "groundplane", "texture": "groundplane",
                                      "texuniform": "true", "texrepeat": "5 5", "reflectance": "0.2"})
    wb = ET.SubElement(m, "worldbody")
    ET.SubElement(wb, "light", {"pos": "0 0 3.5", "dir": "0 0 -1", "directional": "true"})
    ET.SubElement(wb, "geom", {"name": "floor", "size": "0 0 0.05", "pos": "0 0 0",
                               "type": "plane", "material": "groundplane"})
    return m, asset, wb


def build_model_spec(spec, peg_free=True):
    """Build a scene from a shape_gen spec: SO-101 + socket part + boss part.

    The boss part (moved by the arm) has its boss pointing down, standing on the
    boss tip so its body center is at z = d + Hb/2. The socket part sits on the
    floor. `info` carries the motion heights the expert needs.
    """
    import shape_gen as G

    m, asset, wb = _scene_skeleton()
    hx, hy = spec["hole_xy"]
    px, py = spec["peg_xy"]
    Hb, Hs, d = spec["Hb"], spec["Hs"], spec["d"]
    stand_center = d + Hb / 2.0          # boss-part body center when standing (boss tip on floor)
    grasp_z = d + Hb - G.GRASP_INSET     # tool height that grips the body near its top

    p_assets, p_geoms = G.peg_elements(spec)
    s_assets, s_geoms = G.socket_elements(spec)
    for a in p_assets + s_assets:
        asset.append(a)

    socket = ET.SubElement(wb, "body", {"name": "box", "pos": f"{hx:.5f} {hy:.5f} 0",
                                        "quat": G._yaw_quat(spec["hole_yaw"])})
    for g in s_geoms:
        socket.append(g)

    # Boss part oriented to the socket's yaw so their cross-sections line up.
    peg = ET.SubElement(wb, "body", {"name": "peg", "pos": f"{px:.5f} {py:.5f} {stand_center:.5f}",
                                     "quat": G._yaw_quat(spec["hole_yaw"])})
    if peg_free:
        ET.SubElement(peg, "freejoint", {"name": "peg_free"})
    for g in p_geoms:
        peg.append(g)

    with open(SCENE_TMP, "w") as f:
        f.write(ET.tostring(m, encoding="unicode"))
    model = mujoco.MjModel.from_xml_path(SCENE_TMP)
    data = mujoco.MjData(model)
    info = {
        "site_ee": mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_SITE, "gripperframe"),
        "hole_top": np.array([hx, hy, Hs]),         # socket top face
        "box_xy": np.array([hx, hy]),
        "stand_center": stand_center,               # body center standing
        "grasp_z": grasp_z,
        "peg_below_site": grasp_z - stand_center,   # body center offset below the tool while carried
        "insert_site_z": Hs + Hb - G.GRASP_INSET,   # tool height that seats the boss on the hole floor
        "approach_z": d + Hb + 0.05,
        "transit_z": max(Hs, d + Hb) + 0.05,
        "align_z": Hs + 0.05,
    }
    return model, data, info


def preview_camera():
    cam = mujoco.MjvCamera()
    cam.lookat[:] = [0.15, 0.0, 0.04]
    cam.distance = 0.55
    cam.azimuth = 150.0
    cam.elevation = -20.0
    return cam
