"""Partition the common legal solid into disjoint material cells.

Every graph node is a real, pre-carved finite solid. Edges require a shared
face of positive area, or a positive-volume overlap with an immutable head.
"""
from collections import defaultdict
from itertools import product
from pathlib import Path
import json
import pickle
import time

import manifold3d as md
import numpy as np
import trimesh
from scipy.sparse.csgraph import connected_components
from scipy.spatial import ConvexHull
from shapely.geometry import Polygon, box
from shapely.ops import unary_union

from step4_connect_support import build_coupled_saddle as S
from step4_connect_support.material_network import adjacency


def union(parts):
    return md.Manifold.batch_boolean(list(parts), md.OpType.Add)


def prepare(case, placement, work):
    work = Path(work); work.mkdir(parents=True, exist_ok=True)
    bases, offsets, directions = (np.asarray(placement[k]) for k in ('bases', 'offsets', 'directions'))
    key = dict(inputs=S.I.hashes(case.paths), bases=bases.tolist(), offsets=offsets.tolist(),
               directions=directions.tolist(), relief=S.RELIEF, length=S.SWEEP_LENGTH,
               sweep_code=S.I.sha256(Path(S.swept_solid.__code__.co_filename)))
    keyfile = work/'common_space_key.json'
    cached = keyfile.exists() and json.loads(keyfile.read_text()) == key
    sweeps = []
    for k, task in enumerate(case.tasks):
        path = work/f'sweep{k}.npz'
        if cached and path.exists():
            z = np.load(path); sweep = trimesh.Trimesh(z['v'], z['f'], process=False)
        else:
            obj = trimesh.Trimesh(task.domain.mesh.vertices@bases[k]+offsets[k], task.domain.mesh.faces, process=False)
            sweep = S.swept_solid(obj, -S.SWEEP_LENGTH*directions[k]@bases[k])
            np.savez_compressed(path, v=sweep.vertices, f=sweep.faces)
        sweeps.append(sweep)
    path = work/'forbidden.npz'
    if cached and path.exists():
        z = np.load(path); forbidden = S.solid(trimesh.Trimesh(z['v'], z['f'], process=False))
    else:
        relief = md.Manifold.cube([2*S.RELIEF/S.SCALE]*3).translate([-S.RELIEF/S.SCALE]*3)
        forbidden = union(S.solid(s).minkowski_sum(relief) for s in sweeps)
        mesh = S.unpack(forbidden); np.savez_compressed(path, v=mesh.vertices, f=mesh.faces)
    keyfile.write_text(json.dumps(key, indent=2))
    heads = []; records = []
    for k, (groups, cells) in enumerate(zip(case.groups, case.heads)):
        for contact, pieces in zip(groups, cells):
            head = union(S.solid(S.G.hull_mesh(v@bases[k]+offsets[k])) for v in pieces)
            heads.append(head)
            records.append(dict(index=len(records), candidate_id=contact['candidate_id'],
                                head_pose=case.poses[k], role='immutable_contact_head'))
    return dict(key=key, sweeps=sweeps, forbidden=forbidden, heads=heads,
                records=records, bases=bases, offsets=offsets, directions=directions)


def trim_floors(solid, bases, offsets):
    for b, o in zip(bases, offsets):
        solid = solid.trim_by_plane(b[2].tolist(), float(b[2]@o/S.SCALE))
    return solid


def plane_polygon(mesh, normal, offset, coordinates):
    """Actual coplanar boundary triangles, not a projected bounding polygon."""
    on = np.abs(mesh.vertices@normal-offset) < 2e-9
    triangles = mesh.faces[on[mesh.faces].all(1)]
    if not len(triangles): return Polygon()
    xy = mesh.vertices@coordinates
    return unary_union([Polygon(xy[f]) for f in triangles if Polygon(xy[f]).area > 1e-14])


def floor_vertices(mesh, bases, offsets):
    result = []
    for b, o in zip(bases, offsets):
        poly = plane_polygon(mesh, b[2], float(b[2]@o), b[:2].T)
        if poly.area < 1e-6:
            result.append(np.empty((0, 2))); continue
        vertices = mesh.vertices[np.abs((mesh.vertices-o)@b[2]) < 2e-9]
        xy = (vertices-o)@b[:2].T
        if len(xy) >= 3:
            xy = xy[ConvexHull(xy).vertices]
        result.append(xy)
    return result


def build_graph(case, context, work, step=.008, padding=.03, joint_area=4e-6):
    start = time.monotonic(); work = Path(work)
    key = dict(context=context['key'], step=step, padding=padding, joint_area=joint_area,
               code=S.I.sha256(Path(__file__)))
    cache = work/f'graph_{step:.4f}_{padding:.3f}.pickle'
    if cache.exists():
        # This is a private cache generated by this module, never an input file
        # supplied by the object, user, or an external service.
        with cache.open('rb') as f: saved = pickle.load(f)
        if saved['key'] == key:
            print('Reusing material graph:', saved['stats'], flush=True)
            return saved
    bases, offsets = context['bases'], context['offsets']
    heads = context['heads']; head_meshes = [S.unpack(h) for h in heads]
    support = [m.vertices for m in head_meshes]
    for k, xy in enumerate(case.demands):
        rim = xy[ConvexHull(xy).vertices]
        support.append(np.c_[rim, np.zeros(len(rim))]@bases[k]+offsets[k])
    points = np.vstack(support)
    origin = np.floor((points.min(0)-padding)/step)*step
    shape = np.ceil((points.max(0)+padding-origin)/step).astype(int)
    blank = md.Manifold.cube((shape*step/S.SCALE).tolist()).translate((origin/S.SCALE).tolist())
    free = trim_floors(blank, bases, offsets)-context['forbidden']
    meshes = list(head_meshes); cells = [None]*len(heads); costs = [0.]*len(heads)
    by_cell = defaultdict(list); full_cell = [False]*len(heads)
    head_union = union(heads)
    hlow = np.array([m.bounds[0] for m in head_meshes]); hhigh = np.array([m.bounds[1] for m in head_meshes])
    stack = [(free, np.zeros(3, int), shape)]
    while stack:
        solid, lo, hi = stack.pop()
        if solid.is_empty(): continue
        extent = hi-lo
        if extent.max() > 1:
            axis = int(np.argmax(extent)); mid = (lo[axis]+hi[axis])//2
            normal = np.eye(3)[axis]
            positive, negative = solid.split_by_plane(normal.tolist(), float((origin[axis]+mid*step)/S.SCALE))
            high_lo = lo.copy(); high_lo[axis] = mid
            low_hi = hi.copy(); low_hi[axis] = mid
            stack.append((positive, high_lo, hi)); stack.append((negative, lo, low_hi))
            continue
        for piece in solid.decompose():
            volume = float(piece.volume())*S.SCALE**3
            if volume < .025*step**3: continue
            mesh = S.unpack(piece)
            near = np.any(np.all(mesh.bounds[1] >= hlow, axis=1) & np.all(mesh.bounds[0] <= hhigh, axis=1))
            added = volume
            if near:
                added -= float((piece^head_union).volume())*S.SCALE**3
            index = len(meshes); meshes.append(mesh); cells.append(tuple(lo)); costs.append(max(0., added)*1e6)
            full_cell.append(abs(volume-step**3) < 1e-12)
            by_cell[tuple(lo)].append(index)
        if len(meshes) % 2000 == 0:
            print('Partitioned material nodes:', len(meshes), flush=True)
    print('Material cells:', len(meshes), 'grid', shape.tolist(), 'building physical adjacency', flush=True)
    face_cache = {}
    def face(index, axis, side):
        key = index, axis, side
        if key not in face_cache:
            axes = [a for a in range(3) if a != axis]
            lo = origin+np.array(cells[index])*step
            if full_cell[index]:
                poly = box(*lo[axes], *(lo[axes]+step))
            else:
                poly = plane_polygon(meshes[index], np.eye(3)[axis], lo[axis]+side*step, np.eye(3)[:, axes])
            face_cache[key] = poly
        return face_cache[key]
    edges = []
    for cell, ids in by_cell.items():
        for axis in range(3):
            neighbor = list(cell); neighbor[axis] += 1
            for i in ids:
                for j in by_cell.get(tuple(neighbor), []):
                    if full_cell[i] and full_cell[j]:
                        edges.append((i, j)); continue
                    if face(i, axis, 1).intersection(face(j, axis, 0)).area >= joint_area:
                        edges.append((i, j))
    bounds = np.array([m.bounds for m in meshes])
    for i, head in enumerate(heads):
        possible = np.flatnonzero(np.all(bounds[:, 1] > hlow[i]+1e-7, axis=1) & np.all(bounds[:, 0] < hhigh[i]-1e-7, axis=1))
        for j in possible:
            if j <= i: continue
            if float((head^S.solid(meshes[j])).volume())*S.SCALE**3 > 1e-10:
                edges.append((i, int(j)))
    edges = np.array(edges, int).reshape(-1, 2)
    _, labels = connected_components(adjacency(len(meshes), edges), directed=False)
    if len(set(labels[:len(heads)])) != 1:
        degrees = np.bincount(edges.ravel(), minlength=len(meshes))[:len(heads)]
        raise RuntimeError(f'Heads do not share a material component: labels={labels[:len(heads)].tolist()}, degrees={degrees.tolist()}')
    keep = np.flatnonzero(labels == labels[0]); mapping = np.full(len(meshes), -1); mapping[keep] = np.arange(len(keep))
    valid = (mapping[edges] >= 0).all(1); edges = mapping[edges[valid]]
    meshes = [meshes[i] for i in keep]
    floors = [floor_vertices(m, bases, offsets) for m in meshes]
    saved = dict(key=key, vertices=[m.vertices for m in meshes], faces=[m.faces for m in meshes],
        edges=edges, cost=np.asarray(costs)[keep], floors=floors, heads=list(range(len(heads))),
        stats=dict(nodes=len(meshes), edges=len(edges), step_m=step, padding_m=padding,
                   minimum_joint_area_m2=joint_area, minimum_cell_volume_m3=.025*step**3,
                   floor_node_counts=[sum(bool(len(f[k])) for f in floors) for k in (0, 1)],
                   graph_build_seconds=time.monotonic()-start,
                   material_cost='disjoint clipped cells, immutable head overlaps subtracted'))
    with cache.open('wb') as f: pickle.dump(saved, f, protocol=5)
    print('Material graph ready:', saved['stats'], flush=True)
    return saved


def material_solid(graph, selected):
    # A common 1 pm coordinate grid prevents independent Mesh64 round trips
    # from separating the two copies of the same partition face. Heads remain
    # byte-for-byte geometrically unchanged. Full acceptance follows assembly.
    return union(S.solid(trimesh.Trimesh(graph['vertices'][i] if i in graph['heads'] else
                 np.round(graph['vertices'][i], 12), graph['faces'][i], process=False))
                 for i in np.flatnonzero(selected))


def regularize_export(full, heads, radius=1e-6):
    """Remove accidental zero-width edge contacts, without cutting any head.

    A manifold may duplicate vertex indices at a diagonal cell contact. STL
    cannot preserve that distinction. Cut a 1 um channel around only those
    nonmanifold edges; this must not change the single connected component.
    Full contact, floor, withdrawal and load checks follow this operation.
    """
    original_volume = full.volume(); records = []
    head_union = union(heads)
    corners = np.array(list(product([-radius, radius], repeat=3)))
    for iteration in range(4):
        mesh = S.unpack(full)
        vertices, inverse = np.unique(mesh.vertices, axis=0, return_inverse=True)
        merged = trimesh.Trimesh(vertices, inverse[mesh.faces], process=False)
        if merged.is_watertight and merged.is_winding_consistent:
            return full, dict(channel_radius_m=radius, repaired_edges=records,
                removed_volume_cm3=float((original_volume-full.volume())*S.SCALE**3*1e6))
        counts = np.bincount(merged.edges_unique_inverse)
        bad = merged.edges_unique[counts > 2]
        if not len(bad): break
        cutters = union(S.solid(S.G.hull_mesh((vertices[edge, None]+corners).reshape(-1, 3))) for edge in bad)
        full = full-(cutters-head_union)
        records.extend(vertices[bad].tolist())
        if len(full.decompose()) != 1:
            raise RuntimeError('Removing zero-width contacts disconnected the physical fixture')
    raise RuntimeError('Could not regularize coincident edges while preserving the immutable heads')
