"""Run true head-origin growth for eight current groups plus the historical copy."""
import argparse
import json
from pathlib import Path
import shutil
import sys
import time
import numpy as np
import trimesh
sys.path.insert(0,str(Path(__file__).resolve().parent.parent))
from step3_scheculer import contacts as I
from step4_connect_support.baseline_current import coverage_growth as H,run_copied_reference as C
from step4_connect_support.baseline_current import boxed_support as F,deterministic_space as D
from step4_connect_support.baseline_current import build_coupled_saddle as S,render_compact_images as V
from step4_connect_support.baseline_current.run_thick_batch import GROUPS,ROOT

NORMAL_READ=F.read_case

def read(group,out):
    return C.historical_case(group,out) if group.name=='pose1+3copied' else NORMAL_READ(group,out)
F.read_case=read

def run(name):
    started=time.monotonic()
    group=ROOT/name;source=group/'step4/data/boxed_support';out=group/'step4/data/growing_support'
    # Keep the successful domain and try direct growth there first.
    reference=I.check_report(source/'report.json')
    backup=group/'step4/data/history/before_adaptive_ground_growth'
    if not backup.exists():
        backup.mkdir(parents=True)
        for p in out.iterdir():
            if p.is_file():shutil.copy2(p,backup/p.name)
    growth=H.CoverageGrow(group);report=growth.run(pitch=.008)
    attempts=[]
    constructed=growth.final_solid
    cores=growth.core_solids+[(f'beam_{j}',p) for j,p in enumerate(growth.beams)]+[(f'sole_{j}',p) for j,p in enumerate(growth.original_soles)]
    checks=[dict(name=n,missing_volume_m3=abs(float((p-constructed).volume()))*S.SCALE**3) for n,p in cores]
    assert all(p['missing_volume_m3']<=8e-14 for p in checks),[p for p in checks if p['missing_volume_m3']>8e-14]
    report['construction']['method']='Fast head growth with adaptive ground coverage; no prescribed foot targets'
    report['construction']['beam_radius_m']=.003 if name=='pose1+3copied' else .0026
    report['minimum_branch_thickness']=dict(minimum_required_diameter_mm=5.,guaranteed_inscribed_beam_diameter_mm=growth.guaranteed_radius*2000,
        sole_thickness_mm=5.,foot_column_height_mm=6.,local_branches=growth.thickness,constructed_unclipped_core_checks=checks,
        all_complete_cores_preserved=True,scope='complete rods and foot cores; recorded short original-contact transitions/edges excluded')
    report['direct_growth_attempts']=attempts
    report['provenance']['code'].update(I.hashes([Path(__file__),Path(H.__file__),Path(C.__file__)]))
    if name=='pose1+3copied':report['historical_reference']=dict(source_head_id_count=5,physical_contact_patch_count=6,strict_shared_head_registration_passed=False,archived_pose_revision=True)
    I.save(out/'report.json',report)
    objects=[]
    for k,task in enumerate(growth.case.tasks):
        mesh=task.domain.mesh.copy();mesh.vertices=mesh.vertices@growth.bases[k]+growth.offsets[k]
        filename='object_'+task.pose+'_fixture.obj';D.export_exact_obj(mesh,out/filename);objects.append(dict(pose=task.pose,mesh=filename))
    boxed=I.check_report(source/'report.json')
    I.save(out/'stages.json',dict(placement=report['placement'],poses=growth.case.poses,objects=objects,object_mesh=objects[0]['mesh'],reference_pose=growth.case.poses[0],coordinate_frame='fixture',
        ideal_space_budget=boxed['ideal_box'],accepted_space_budget=report['space_budget'],actual_space_budget=report['space_budget'],
        camera_view_fixture=((-growth.directions[0]+np.array([0,0,.65]))@growth.bases[0]).tolist(),
        growth_journal=report['construction']['growth_journal'],partial_stage_step_count=report['construction']['partial_stage_step_count'],
        initial_head_name=report['construction']['initial_head_name'],
        stages=[dict(key=k,mesh=f,label=l) for k,f,l in [('roots','roots.obj','Original contacts'),('seed_targets','seed_targets.obj','Actual head starts'),('partial_growth','partial_growth.obj','Direct growth from heads'),('shared_tree','shared_tree.obj','Shared grown branches'),('final','shape.obj','Verified final support')]]))
    # No exported-model recheck or independent replay in the active pipeline.
    (out/'replay.json').unlink(missing_ok=True)
    report['timing_seconds']['driver_before_overview']=time.monotonic()-started
    I.save(out/'report.json',report)
    # Previous process image will be regenerated by the parent from the journal.
    (group/'step4/construction_steps.png').unlink(missing_ok=True)
    V.render(group,'growing_support')
    if name=='pose1+3copied':
        shutil.copyfile(out/'shape.obj',group/'step4/shape.obj')
        I.save(group/'step4/data/report.json',dict(report,artifacts={'growing_support/'+p:d for p,d in report['artifacts'].items()}))
    I.check_report(out/'report.json');I.check_report(group/'step4/data/compact_visualization.json')
    row=dict(group=name,passed=True,volume_cm3=report['volume_cm3'],space_budget=report['space_budget'],construction=report['construction'],seconds=report['seconds'],timing_seconds=dict(report['timing_seconds'],driver_with_overview=time.monotonic()-started))
    print('TRUE HEAD GROWTH DONE',name,'direct',row['construction']['direct_connection_count'],'fallback',row['construction']['fallback_route_count'],flush=True)
    return row

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--groups',nargs='+',default=['pose1+3copied']+GROUPS);a=p.parse_args()
    before=C.tree_hash(ROOT/'pose1+3')
    rows=[run(n) for n in a.groups]
    assert before==C.tree_hash(ROOT/'pose1+3')
    I.save(ROOT/GROUPS[-1]/'step4/data/growing_support/direct_growth_batch.json',dict(passed=True,groups=rows,original_reference_unchanged=True))
